### ISSUE TITLE
fetch file from IPFS.

### ISSUE THREAD

**Issue by Amosharid** [emendir/IPFS-Toolkit-Python#4]
Hi there,
I've been trying to find the write method to fetch a file from the IPFS.
Does such a method exist in this library?

**Comment by PaTara43** [comment]
hey there. It seems to be this
https://github.com/emendir/IPFS-Toolkit-Python/blob/master/ipfshttpclient2/client/files.py#L383

**Comment by emendir** [comment]
Hello,

Previously in was `IPFS_API.DownloadFile()`
In v0.4.1 this has been replaced with `IPFS_API.Download()`, which is able to download folders from IPFS instead of just files.

Cheers!
