### ISSUE TITLE
Why files are UNPINNED after published? 

### ISSUE THREAD

**Issue by Marionette-yixuan** [emendir/IPFS-Toolkit-Python#5]
I use `cid = ipfs_api.publish(file_name)` to publish a file to IPFS, 
and `ipfs-cluster-ctl status cid` shows that the file is unpinned on every peer.
I tried `ipfs_api.pin(cid)` but it's not helping.

What should I do?

**Comment by abrichr** [comment]
@Marionette-yixuan can you please share how you resolved this issue? Thank you! 🙏
